import { Request, Response } from "express";
import { encryptAndSend } from "../../../services/crypto/encryptionHelpers";

export const get = (req: Request, res: Response) => {
  const data = {
    banner_list:{
      outer_banner_list:[],
      resident_banner_list:[]
    },
    campaign_list:{
      event_campaign_list:[],
      island_campaign_list:[],
      m16_campaign_list:[],
      point_campaign_list:[],
      purchase_campaign_list:[],
      score_campaign_list:[],
      strengthen_campaign_list:[]
    },
    emergency_info_list:[],
    free_auto:0,
    fuwafuwa_time:0,
    increase_info:{
      max_num:0,
      now_num:0,
      remain_time:0
    },
    invite_num:0,
    navigationNum:{
      notClearNum:0,
      notClearNumLimited:0,
      notReceivedNum:0,
      notReceivedNumLimited:0,
    },
    new_mail:0,
    new_present:0,
    offer_products:[],
    purchase_increase_info:[],
    purchase_stamp_info:[],
    stretch_effect_info:{
      exchange_present:0,
      free_auto_add:0,
      free_auto_infinity:0,
      increase_add:0,
      increase_inf:0,
      mst_event_info_id:0,
      time_info:{
        exchange_present:{
          end:0,
          end_remain:0,
          start:0,
          start_remain:0
        },
        free_auto_add:{
          end:0,
          end_remain:0,
          start:0,
          start_remain:0
        },
        free_auto_infinity:{
          end:0,
          end_remain:0,
          start:0,
          start_remain:0
        },
        increase_add:{
          end:0,
          end_remain:0,
          start:0,
          start_remain:0
        }
      }
    },
    treasureBanner:{
      type:0,
      url:"",
      unreadCount:0
    }
  };
  encryptAndSend(data, res,req);
};
